
server:  port: 8888
  
spring:
  cloud:
    config:
      server:
        encrypt:
            enabled: false
        git:
          uri: https://github.com/brunosantanati/microservicos-parte-2/tree/main/microservicos-config/
          search-paths: fornecedor